/***************************************************************************//**
* \file cy_fr_api_init.c
* \version 1.0
*
* \brief
* Initialize the FlexRay Communication Controller with a *.chi file
*
* This file contains the user interface to initialize the FlexRay CC by using a
* *.chi file. The chi file comprised all setting for the E-Ray FlexRay CC
*
********************************************************************************
* \copyright
* Copyright 2016-2017, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif


#include "flexray/api/cy_fr_api_global.h"
#include "flexray/api/cy_fr_api_init.h"
#include "flexray/ccal/cy_fr_ccal_init.h"
#include "flexray/fhal/cy_fr_fhal.h"

/*---------------------------------------------------------------------------------*/
/** \brief      This function initialize all E-Ray registers with a *.chi file
                ( generated by an external tool e.g. FlexConfig by Star Cooperation ). 

    \param[in]  base                     Pointer to FlexRay register base
    \param[in]  cy_fr_chi_inc_func_ptr   Pointer to user provided function that
                                         has #included the CHI file in its body
    
    \retval     CY_FR_OKAY         In case of success
    \retval     CY_FR_NOT_CONFIG   In case POC Status CONFIG can not be reached
*/
/*---------------------------------------------------------------------------------*/
CY_FR_RETURN_TYPE cy_fr_api_init_chi( volatile stc_FLEXRAY_t *            base,
                                      CY_FR_CHI_INCLUDE_FUNCTION_PTR_TYPE cy_fr_chi_inc_func_ptr )
{
  return cy_fr_ccal_init_chi(base, cy_fr_chi_inc_func_ptr); /* initialize complete FRCC with a *.chi file and Cypress specific registers */
}



#if defined(__cplusplus)
}
#endif


/* [] END OF FILE */
